name: Update README

on:
  push:
    branches:
      - main
      - 'feature/**readme**'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    env:
      DOCKER_VERSION: 27.3.1

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Docker
        run: |
          curl -L -o "/tmp/docker-${DOCKER_VERSION}.tgz" "https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_VERSION}.tgz" \
          && tar -xz -C /tmp -f "/tmp/docker-${DOCKER_VERSION}.tgz" \
          && sudo mv /tmp/docker/* /usr/bin \
          && docker --version

      - name: Build image
        run: docker build -t drevops/ci-runner:test .

      - name: Update README with package versions
        id: update-readme
        run: ./versions.js "drevops/ci-runner:test" --update-readme README.md --section '## Included packages' || echo "updated=true" >> "$GITHUB_OUTPUT"

      - name: Create Pull Request
        if: steps.update-readme.outputs.updated == 'true'
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Updated README.md with packages versions."
          branch: feature/update-readme-versions
          delete-branch: true
          title: "Updated README.md with packages versions"
          body: |
            This PR updates the "Included packages" section in README.md with the latest package versions from the Docker image.

            **Auto-generated by workflow**

      - name: Enable auto-merge
        if: steps.update-readme.outputs.updated == 'true' && steps.cpr.outputs.pull-request-number
        run: gh pr merge --auto --squash "${{ steps.cpr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
